---
- name: apt install ca-certificates, curl, gnupg
  when: ansible_distribution == "Ubuntu"
  become: yes
  apt:
    pkg:
      - ca-certificates
      - curl
      - gnupg
    state: present
    update_cache: yes
- name: download docker gpg key
  when: ansible_distribution == "Ubuntu"
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /tmp
- name: create directory
  become: yes
  file:
    path: /etc/apt/keyrings
    state: directory
- name: install docker gpg
  become: yes
  shell:
    cmd: cat /tmp/gpg | gpg --dearmor --yes -o /etc/apt/keyrings/docker.gpg; chmod a+r /etc/apt/keyrings/docker.gpg
- name: setup repository
  shell: 
    cmd: echo "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" |  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
- name: install docker setup
  become: yes
  apt:
    pkg: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
- name: restart dockerd
  become: yes
  systemd:
    name: docker
    state: restarted
- name: add user to group docker
  become: yes
  user:
    name: "abhijit"
    groups: docker
    append: yes
